ARTICLE_TYPES:
  default:
    title: Standardseite
    template: standard
  twocolumn:
    title: Zweispaltige Seite
    template: twocolumn
    modules: ['image','weiterleitung','wymeditor']
  newsarticle:
    title: News Artikel
    template: standard