article_types:
  default:
    title: Standardseite
    template: standard
  # Die Startseite unterscheidet sich von der normalen nur durch die ihr zugewiesenen Metainfos.
  start:
    title: Startseite
    template: standard
  twocolumn:
    title: Zweispaltige Seite
    template: twocolumn
    modules: [image, redirect, wymeditor]
  news:
    title: News-Beitrag
    template: newsarticle
    modules: [image, wymeditor]
