metainfo:
  articles:
    page:
      title: alternativer Seitentitel
      datatype: stringline
      params:
        maxlength: 50
      metapage: false
      types: [default, twocolumn, newsarticle]
    date:
      title: News Datum
      datatype: datetime
      metapage: false
      types: [newsarticle]
