metainfo:
  articles:
    page:
      title: alternativer Seitentitel
      datatype: stringline
      params:
        maxlength: 50
      metapage: false
      types: [default, twocolumn]
    author:
      title: Autor
      datatype: stringline
      params:
        maxlength: 50
      helptext: Geben Sie hier Ihren Namen an.
      metapage: false
      types: [newsarticle]
    date:
      title: News Datum
      datatype: datetime
      metapage: false
      types: [newsarticle]
    keyvisual:
      title: Keyvisual
      datatype: medialist
      params: {max: 100}
      metapage: false
      types: [homepage]